version: '2'
services:
  maven:
    build: ./maven
  tomcat:
    image: tomcat:latest
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=mangashare
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
