version: '2'
volumes:
  data: {}
services:
  maven:
    build: ./maven
    hostname: maven
    volumes: 
      - data:/mnt/
  tomcat:
    build: ./tomcat
    hostname: tomcat
    volumes: 
      - data:/mnt/
    expose:
      - "80"
    ports:
      - "8888:8080"
    links:
      - mysql
  mysql:
    image: mysql/mysql-server
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mangashare
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
